name: 'Auto assign reviewers'
description: 'Assign PR reviewers automatically from commits.'
inputs:
  pull-request-number:
    description: 'Number of target pull request'
  ignore-users:
    description: 'A comma separated list of usernames that are ignored'
runs:
  using: "composite"
  steps:
    - name: Assign reviewers
      id: assign_reviewers
      # SEE: https://github.com/actions/github-script
      uses: actions/github-script@v5
      with:
        script: |
          console.log("Start Auto assing reviewers action. pull-request-number=${{ inputs.pull-request-number }}")

          const ignoreUsers = "${{ inputs.ignore-users }}".split(",").map(s => s.trim()).filter(x => x !== "")

          const pr = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: ${{ inputs.pull-request-number }}
          })
          console.log(pr);
          console.log(pr.user.login);

          // List related commits
          const response = await github.rest.pulls.listCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: ${{ inputs.pull-request-number }}
          })
          console.log(response)
          if (response.status !== 200) {
            throw new Error(`status is ${response.status}`)
          }

          // List commiters
          const commits = response.data
          const reviewer_logins = []
          for (const cm of commits) {
            if (cm.author === undefined || cm.author === null || cm.author.login === undefined || cm.author.login === null) {
              continue
            }

            if (!reviewer_logins.includes(cm.author.login) && !ignoreUsers.includes(cm.author.login)) {
              reviewer_logins.push(cm.author.login)
            }
          }
          console.log("Reviewers: ", reviewer_logins)

          // Assign commiters as reviewer
          const review_request_response = await github.rest.pulls.requestReviewers({
            owner: context.repo.owner,
            repo: context.repo.repo,
            reviewers: reviewer_logins,
            pull_number: ${{ inputs.pull-request-number }}
          })
          console.log(review_request_response)

